// src/app/layout.tsx

import './globals.css'; // Import global styles

export const metadata = {
  title: 'My Next.js App',
  description: 'Generated by create-next-app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        {children} {/* This will render the content of the pages */}
      </body>
    </html>
  );
}
